jobs:
  - job: "Analyze"
    condition: ne(variables['Skip.Analyze'], true)
    variables:
      - template: ../variables/globals.yml
    dependsOn:
    pool:
      vmImage: "windows-2019"
    steps:
      - template: /eng/common/pipelines/templates/steps/analyze-pkg-props.yml
        parameters:
            ServiceDirectory: ${{parameters.ServiceDirectory}}
            Artifacts: ${{parameters.Artifacts}}